// AI-written motion scenes: Claude writes TSX into src/lab/motion/<project>/ (and nowhere else),
// the Lab type-checks it, asks for fixes if needed and registers it for the Player and the renderer.
import fs from 'node:fs';
import path from 'node:path';
import {askClaude} from './ai.mjs';
import {slot} from './jobctx.mjs';
import {run} from './media.mjs';
import {getBrief, saveBrief, sectionsIn, stagePrompt} from './prompts.mjs';
import {ROSTER_SCHEMA} from './schemas.mjs';
import {dirOf, readJson, ROOT, writeJson} from './store.mjs';

export const MOTION_ROOT = path.join(ROOT, 'src', 'lab', 'motion');
const GUIDE = path.join(MOTION_ROOT, 'GUIDE.md');
export const motionDir = (id) => path.join(MOTION_ROOT, id);
const alias = (s) => `m_${s.replace(/[^a-zA-Z0-9]/g, '_')}`;

// The AI writes <file>.draft.tsx; only files that passed the type check are renamed and registered,
// so a block still being written never reaches the Player or another project's render.
const draftOf = (file) => file.replace(/\.tsx$/, '.draft.tsx');
const notesFile = (id) => path.join(dirOf('project', id), 'motion-notes.json');

export const sceneFiles = (id) => {
  const dir = motionDir(id);
  if (!fs.existsSync(dir)) return [];
  const order = (n) => (n === 'sample.tsx' ? 0 : Number(/part-(\d+)/.exec(n)?.[1] ?? 999));
  return fs.readdirSync(dir).filter((n) => /^(sample|part-\d+)\.tsx$/.test(n)).sort((a, b) => order(a) - order(b));
};

// Unchanged files are left alone: a rewrite would trigger the bundler of a render running in parallel.
const writeIfChanged = (file, body) => { if (!fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== body) fs.writeFileSync(file, body); };

/** Rewrites src/lab/motion/<id>/index.ts and the global registry src/lab/motion/index.ts. */
export const writeRegistry = () => {
  fs.mkdirSync(MOTION_ROOT, {recursive: true});
  const projects = fs.readdirSync(MOTION_ROOT).filter((n) => fs.statSync(path.join(MOTION_ROOT, n)).isDirectory());
  const withScenes = [];
  for (const id of projects) {
    const files = sceneFiles(id);
    const idx = path.join(motionDir(id), 'index.ts');
    if (!files.length) { fs.rmSync(idx, {force: true}); continue; }
    writeIfChanged(idx, `// Generated by the Lab — do not edit.\nimport type {MotionScene} from '../../types';\n${files.map((f) => `import {scenes as ${alias(f)}} from './${f.replace(/\.tsx$/, '')}';`).join('\n')}\n\nexport const scenes: MotionScene[] = [${files.map((f) => `...${alias(f)}`).join(', ')}];\n`);
    withScenes.push(id);
  }
  const body = `// Generated by lab/lib/motion.mjs — lists the AI-written motion scenes of each Lab project.\nimport type {MotionScene} from '../types';\n${withScenes.map((id) => `import {scenes as ${alias(id)}} from './${id}';`).join('\n')}\n\nexport const MOTION: Record<string, MotionScene[]> = {${withScenes.map((id) => `\n  '${id}': ${alias(id)},`).join('')}${withScenes.length ? '\n' : ''}};\n`;
  writeIfChanged(path.join(MOTION_ROOT, 'index.ts'), body);
};

export const clearMotion = (id, {keepSample = false} = {}) => {
  const dir = motionDir(id);
  const stale = fs.existsSync(dir) ? fs.readdirSync(dir).filter((n) => /\.tsx(\.broken)?$/.test(n) && !(keepSample && n === 'sample.tsx')) : [];
  for (const f of stale) fs.rmSync(path.join(dir, f), {force: true});
  const notes = readJson(notesFile(id));
  if (notes) writeJson(notesFile(id), keepSample && notes['sample.tsx'] ? {'sample.tsx': notes['sample.tsx']} : {});
  writeRegistry();
};
export const removeMotion = (id) => { fs.rmSync(motionDir(id), {recursive: true, force: true}); writeRegistry(); };

/** TypeScript errors in one motion file (other blocks may be mid-write at the same time, so only this file counts). */
const typecheck = async (id, file) => {
  const {out, err} = await slot('tsc', () => run('npx', ['tsc', '--noEmit', '-p', 'tsconfig.json', '--pretty', 'false'], {allowFail: true}));
  const rel = `src/lab/motion/${id}/${file}(`;
  return (out + err).split('\n').filter((l) => l.startsWith(rel));
};

const MOTION_SCHEMA = {
  type: 'object', additionalProperties: false, required: ['scenes', 'summary'],
  properties: {
    scenes: {type: 'array', items: {type: 'object', additionalProperties: false, required: ['id', 'what'], properties: {id: {type: 'string'}, what: {type: 'string', description: 'O que a cena mostra, em pt-BR'}}}},
    summary: {type: 'string', description: 'Resumo curto em pt-BR'},
  },
};

const perms = (dir) => ({
  tools: ['Read', 'Write', 'Edit', 'Glob', 'Grep'],
  allowed: ['Read', 'Glob', 'Grep', `Write(/${dir}/**)`, `Edit(/${dir}/**)`],
  addDirs: [dir, path.join(ROOT, 'src')],
  system: 'Você é um motion designer sênior que escreve cenas em React/Remotion com TypeScript estrito. Escreva somente nos arquivos pedidos. Responda em português do Brasil.',
  timeoutMs: 25 * 60 * 1000,
});

const videoText = (spec) => {
  const st = spec.style;
  return `${spec.width}×${spec.height} @ ${spec.fps} fps. Paleta do estilo: texto ${st.captions.color}, destaque ${st.captions.highlightColor}, apoio ${st.callouts.accentColor}. Fonte da legenda: ${st.captions.font}. As legendas ficam em ${st.captions.yPct}% da altura${st.captions.enabled ? '' : ' (desligadas)'} — não cubra essa faixa com overlays, ou use hideCaptions.`;
};
const wordsIn = (spec, fromSec, toSec) => spec.words.filter((w) => w.f >= fromSec * spec.fps && w.f < toSec * spec.fps);
const loadSpec = (id) => readJson(path.join(dirOf('project', id), 'spec.json'));

/**
 * Brief, part 2 (after the sample): the approved visual language + what each parallel block animates.
 * `chunks` = [[fromSec, toSec], …] in edit time. Skipped when the sample and the chunks did not change,
 * so edits made in the Briefing tab survive.
 */
export const rosterWithAi = async (id, {model, chunks, force = false}, job) => {
  const spec = loadSpec(id);
  const dir = motionDir(id);
  const sample = path.join(dir, 'sample.tsx');
  if (!spec || !fs.existsSync(sample)) return null;
  const key = `${fs.statSync(sample).mtimeMs}:${chunks.map(([a, b]) => `${a.toFixed(1)}-${b.toFixed(1)}`).join(',')}`;
  const brief = getBrief(id);
  if (!force && brief.rosterKey === key) return brief;
  const notes = readJson(notesFile(id))?.['sample.tsx'];
  const list = chunks.map(([a, b], i) => {
    const w = wordsIn(spec, a, b);
    const text = w.map((x) => x.t).join(' ');
    return `### Bloco ${i + 1} (${a.toFixed(0)}s–${b.toFixed(0)}s, palavras ${w[0]?.ri ?? '–'} a ${w.at(-1)?.ri ?? '–'})\nSeções: ${w.length ? sectionsIn(id, w[0].ri, w.at(-1).ri).replace(/\n/g, '; ') : '—'}\nFala: ${text.length > 900 ? `${text.slice(0, 900)}…` : text || '(sem fala)'}`;
  }).join('\n\n');
  job.step('IA combinando a linguagem visual e o roteiro dos blocos');
  const res = await askClaude({
    prompt: stagePrompt(id, 'roteiro', {guia: GUIDE, amostra: sample, notas_amostra: notes ? `${notes.summary}\n${notes.scenes.map((x) => `- ${x.id}: ${x.what}`).join('\n')}` : '(sem notas, leia o código)', blocos: list}),
    schema: ROSTER_SCHEMA, cwd: dir, model, onLine: (l) => l && job.log(l),
  });
  job.cost(res.costUsd, res.model);
  const blocks = chunks.map(([a, b], i) => {
    const x = res.data.blocks.find((y) => Math.round(y.index) === i + 1) ?? {};
    return {index: i + 1, fromSec: a, toSec: b, focus: x.focus ?? '', avoid: x.avoid ?? '', bridge: x.bridge ?? ''};
  });
  return saveBrief(id, {visual: res.data.visual, blocks, rosterKey: key});
};

/**
 * Generates one scene file covering the edit-time window [fromSec, toSec).
 * file: 'sample.tsx' or 'part-N.tsx'. `block` (parts only) = {index, total} — its roster line comes from the brief.
 */
export const generateMotion = async (id, {model, feedback, file, fromSec, toSec, block}, job) => {
  const spec = loadSpec(id);
  if (!spec) throw new Error('Monte a edição antes do motion');
  const dir = motionDir(id);
  fs.mkdirSync(dir, {recursive: true});
  const target = path.join(dir, file);
  const draft = draftOf(file);
  const draftPath = path.join(dir, draft);
  fs.rmSync(draftPath, {force: true});
  const words = wordsIn(spec, fromSec, toSec);
  if (!words.length) { job.log(`Sem fala entre ${fromSec.toFixed(1)}s e ${toSec.toFixed(1)}s — pulando`); return null; }
  const common = {
    guia: GUIDE, video: videoText(spec), arquivo: draftPath,
    de: fromSec.toFixed(1), ate: toSec.toFixed(1),
    trecho: words.map((w) => `${w.ri}:${w.t}@${(w.f / spec.fps).toFixed(1)}s`).join(' '),
    primeira: words[0].ri, ultima: words.at(-1).ri, secao: sectionsIn(id, words[0].ri, words.at(-1).ri),
  };
  let ask;
  if (block) {
    const roster = getBrief(id).blocks ?? [];
    const mine = roster.find((x) => x.index === block.index) ?? {};
    const near = (i) => { const x = roster.find((y) => y.index === i); return x ? `${x.fromSec.toFixed(0)}s–${x.toSec.toFixed(0)}s: ${x.focus}${x.bridge ? ` (emenda: ${x.bridge})` : ''}` : 'nenhum (é a ponta do vídeo ou a amostra aprovada)'; };
    ask = stagePrompt(id, 'motion-bloco', {
      ...common, bloco: block.index, total_blocos: block.total, amostra: path.join(dir, 'sample.tsx'),
      foco: mine.focus || 'siga a fala e a intenção da seção', evitar: mine.avoid || 'repetir a mesma cena em sequência', emenda: mine.bridge || 'entradas e saídas limpas',
      anterior: near(block.index - 1), proximo: near(block.index + 1),
    });
  } else {
    ask = stagePrompt(id, 'motion-amostra', {...common, ajuste_anterior: feedback ? `\n## Ajuste pedido na amostra anterior\n${feedback}\n` : ''});
  }

  job.step(`IA escrevendo o motion (${file.replace('.tsx', '')})`);
  const res = await askClaude({prompt: ask, schema: MOTION_SCHEMA, cwd: dir, model, onLine: (l) => l && job.log(l), ...perms(dir)});
  job.cost(res.costUsd, res.model);
  if (!fs.existsSync(draftPath)) throw new Error(`A IA não criou ${draft}`);

  // tsc checks every file under src/, so the new scenes are validated before the Player/renderer import them.
  job.step(`Checando o código (${file.replace('.tsx', '')})`);
  let errors = await typecheck(id, draft);
  for (let round = 1; errors.length && round <= 2; round++) {
    job.log(`${errors.length} erro(s) de TypeScript — pedindo correção (${round}/2)`);
    const fix = await askClaude({
      prompt: stagePrompt(id, 'motion-correcao', {arquivo: draftPath, guia: GUIDE, erros: errors.slice(0, 40).join('\n')}),
      schema: MOTION_SCHEMA, cwd: dir, model, onLine: (l) => l && job.log(l), ...perms(dir),
    });
    job.cost(fix.costUsd, fix.model);
    errors = await typecheck(id, draft);
  }
  if (errors.length) {
    fs.renameSync(draftPath, `${target}.broken`);
    throw new Error(`O motion gerado não compilou (arquivo guardado como ${file}.broken):\n${errors.slice(0, 8).join('\n')}`);
  }
  fs.renameSync(draftPath, target);
  writeRegistry();
  // Kept for the effects list under the video and for the roster step.
  writeJson(notesFile(id), {...(readJson(notesFile(id)) ?? {}), [file]: {summary: res.data.summary, scenes: res.data.scenes}});
  job.log(res.data.summary);
  for (const sc of res.data.scenes) job.log(`• ${sc.id}: ${sc.what}`);
  return res.data;
};

// `node lab/lib/motion.mjs` regenerates the registry (runs before `npm run dev`/`lint` on a fresh clone).
if (process.argv[1] && path.resolve(process.argv[1]) === path.join(ROOT, 'lab', 'lib', 'motion.mjs')) writeRegistry();
