// AI-written motion scenes: Claude writes TSX into src/lab/motion/<project>/ (and nowhere else),
// the Lab type-checks it, asks for fixes if needed and registers it for the Player and the renderer.
import fs from 'node:fs';
import path from 'node:path';
import {askClaude} from './ai.mjs';
import {run} from './media.mjs';
import {readJson, ROOT} from './store.mjs';

export const MOTION_ROOT = path.join(ROOT, 'src', 'lab', 'motion');
const GUIDE = path.join(MOTION_ROOT, 'GUIDE.md');
export const motionDir = (id) => path.join(MOTION_ROOT, id);
const alias = (s) => `m_${s.replace(/[^a-zA-Z0-9]/g, '_')}`;

const sceneFiles = (id) => {
  const dir = motionDir(id);
  if (!fs.existsSync(dir)) return [];
  const order = (n) => (n === 'sample.tsx' ? 0 : Number(/part-(\d+)/.exec(n)?.[1] ?? 999));
  return fs.readdirSync(dir).filter((n) => /\.tsx$/.test(n)).sort((a, b) => order(a) - order(b));
};

/** Rewrites src/lab/motion/<id>/index.ts and the global registry src/lab/motion/index.ts. */
export const writeRegistry = () => {
  fs.mkdirSync(MOTION_ROOT, {recursive: true});
  const projects = fs.readdirSync(MOTION_ROOT).filter((n) => fs.statSync(path.join(MOTION_ROOT, n)).isDirectory());
  const withScenes = [];
  for (const id of projects) {
    const files = sceneFiles(id);
    const idx = path.join(motionDir(id), 'index.ts');
    if (!files.length) { fs.rmSync(idx, {force: true}); continue; }
    fs.writeFileSync(idx, `// Generated by the Lab — do not edit.\nimport type {MotionScene} from '../../types';\n${files.map((f) => `import {scenes as ${alias(f)}} from './${f.replace(/\.tsx$/, '')}';`).join('\n')}\n\nexport const scenes: MotionScene[] = [${files.map((f) => `...${alias(f)}`).join(', ')}];\n`);
    withScenes.push(id);
  }
  const body = `// Generated by lab/lib/motion.mjs — lists the AI-written motion scenes of each Lab project.\nimport type {MotionScene} from '../types';\n${withScenes.map((id) => `import {scenes as ${alias(id)}} from './${id}';`).join('\n')}\n\nexport const MOTION: Record<string, MotionScene[]> = {${withScenes.map((id) => `\n  '${id}': ${alias(id)},`).join('')}${withScenes.length ? '\n' : ''}};\n`;
  const reg = path.join(MOTION_ROOT, 'index.ts');
  if (!fs.existsSync(reg) || fs.readFileSync(reg, 'utf8') !== body) fs.writeFileSync(reg, body);
};

export const clearMotion = (id, {keepSample = false} = {}) => {
  for (const f of sceneFiles(id)) if (!(keepSample && f === 'sample.tsx')) fs.rmSync(path.join(motionDir(id), f), {force: true});
  writeRegistry();
};
export const removeMotion = (id) => { fs.rmSync(motionDir(id), {recursive: true, force: true}); writeRegistry(); };

/** TypeScript errors that belong to this project's motion folder. */
const typecheck = async (id) => {
  const {out, err} = await run('npx', ['tsc', '--noEmit', '-p', 'tsconfig.json', '--pretty', 'false'], {allowFail: true});
  const rel = `src/lab/motion/${id}/`;
  return (out + err).split('\n').filter((l) => l.startsWith(rel));
};

const MOTION_SCHEMA = {
  type: 'object', additionalProperties: false, required: ['scenes', 'summary'],
  properties: {
    scenes: {type: 'array', items: {type: 'object', additionalProperties: false, required: ['id', 'what'], properties: {id: {type: 'string'}, what: {type: 'string', description: 'O que a cena mostra, em pt-BR'}}}},
    summary: {type: 'string', description: 'Resumo curto em pt-BR'},
  },
};

const perms = (dir) => ({
  tools: ['Read', 'Write', 'Edit', 'Glob', 'Grep'],
  allowed: ['Read', 'Glob', 'Grep', `Write(/${dir}/**)`, `Edit(/${dir}/**)`],
  addDirs: [dir, path.join(ROOT, 'src')],
  system: 'Você é um motion designer sênior que escreve cenas em React/Remotion com TypeScript estrito. Escreva somente nos arquivos pedidos. Responda em português do Brasil.',
  timeoutMs: 25 * 60 * 1000,
});

/**
 * Generates one scene file covering the output-time window [fromSec, toSec).
 * file: 'sample.tsx' or 'part-N.tsx'. For parts, the approved sample is the visual reference.
 */
export const generateMotion = async (id, {model, prompt, feedback, file, fromSec, toSec}, job) => {
  const spec = readJson(path.join(ROOT, 'lab', 'data', 'projects', id, 'spec.json'));
  if (!spec) throw new Error('Monte a edição antes do motion');
  const dir = motionDir(id);
  fs.mkdirSync(dir, {recursive: true});
  const target = path.join(dir, file);
  const fps = spec.fps;
  const words = spec.words.filter((w) => w.f >= fromSec * fps && w.f < toSec * fps);
  if (!words.length) { job.log(`Sem fala entre ${fromSec.toFixed(1)}s e ${toSec.toFixed(1)}s — pulando`); return null; }
  const transcript = words.map((w) => `${w.ri}:${w.t}@${(w.f / fps).toFixed(1)}s`).join(' ');
  const sample = path.join(dir, 'sample.tsx');
  const isPart = file !== 'sample.tsx';
  const s = spec.style;

  const ask = `Crie as cenas de MOTION de um trecho de vídeo editado.

## Leia antes
1. ${GUIDE} — contrato, toolkit e regras (obrigatório).
${isPart && fs.existsSync(sample) ? `2. ${sample} — AMOSTRA APROVADA pelo cliente. Mantenha exatamente a mesma linguagem visual (cores, fontes, tipos de animação, densidade, uso de câmera). Pode copiar componentes dela para o seu arquivo (não importe de lá).` : '2. Opcional: 1 ou 2 arquivos de src/vsl/scenes/ como referência de nível.'}

## Pedido de motion do cliente
${prompt?.trim() || 'Motion graphics que reforcem as ideias-chave da fala: números, listas, contrastes, CTAs. Visual limpo e moderno.'}
${feedback ? `\n## Ajuste pedido na amostra anterior\n${feedback}\n` : ''}
## Vídeo
${spec.width}×${spec.height} @ ${fps} fps. Paleta do estilo: texto ${s.captions.color}, destaque ${s.captions.highlightColor}, apoio ${s.callouts.accentColor}. Fonte da legenda: ${s.captions.font}. As legendas ficam em ${s.captions.yPct}% da altura${s.captions.enabled ? '' : ' (desligadas)'} — não cubra essa faixa com overlays, ou use hideCaptions.

## Trecho (${fromSec.toFixed(1)}s–${toSec.toFixed(1)}s da edição). Formato índice:palavra@tempo
${transcript}

## Tarefa
Escreva o arquivo ${target} exportando \`scenes: MotionScene[]\`. Use apenas índices de palavra deste trecho (${words[0].ri} a ${words.at(-1).ri}). Distribua as cenas conforme o pedido (em geral 1 cena a cada 3–8 s de fala, alternando 'over' e 'full' com câmera em janela quando fizer sentido). Não escreva nenhum outro arquivo.`;

  job.step(`IA escrevendo o motion (${file.replace('.tsx', '')})`);
  const res = await askClaude({prompt: ask, schema: MOTION_SCHEMA, cwd: dir, model, onLine: (l) => l && job.log(l), ...perms(dir)});
  job.cost(res.costUsd, res.model);
  if (!fs.existsSync(target)) throw new Error(`A IA não criou ${file}`);

  // tsc checks every file under src/, so the new scenes are validated before the Player/renderer import them.
  job.step('Checando o código gerado');
  let errors = await typecheck(id);
  for (let round = 1; errors.length && round <= 2; round++) {
    job.log(`${errors.length} erro(s) de TypeScript — pedindo correção (${round}/2)`);
    const fix = await askClaude({
      prompt: `O arquivo ${target} não compila. Corrija SOMENTE esse arquivo, mantendo o design. Regras em ${GUIDE}.\n\nErros:\n${errors.slice(0, 40).join('\n')}`,
      schema: MOTION_SCHEMA, cwd: dir, model, onLine: (l) => l && job.log(l), ...perms(dir),
    });
    job.cost(fix.costUsd, fix.model);
    errors = await typecheck(id);
  }
  if (errors.length) {
    fs.renameSync(target, `${target}.broken`);
    throw new Error(`O motion gerado não compilou (arquivo guardado como ${file}.broken):\n${errors.slice(0, 8).join('\n')}`);
  }
  writeRegistry();
  job.log(res.data.summary);
  for (const sc of res.data.scenes) job.log(`• ${sc.id}: ${sc.what}`);
  return res.data;
};

// `node lab/lib/motion.mjs` regenerates the registry (runs before `npm run dev`/`lint` on a fresh clone).
if (process.argv[1] && path.resolve(process.argv[1]) === path.join(ROOT, 'lab', 'lib', 'motion.mjs')) writeRegistry();
