import fs from "fs";
const {chunks, words} = JSON.parse(fs.readFileSync("scripts/chunks.json", "utf8"));
const FPS = 30;
// speech spans to keep (source seconds). Chunk 0 is split to drop the repeated "você acabou de comprar".
let spans = chunks.map(([a, b]) => [a, b]).filter(([a, b]) => b - a > 0.3);
spans = spans.flatMap(([a, b]) => (a < 30 && b > 48 ? [[a, 47.64]] : [[a, b]])).filter(([a, b]) => b - a > 0.05);
// chunk starting at 49.68 was already its own span; drop the zero-length helper
spans = spans.filter(([a, b]) => b > a);
const PRE = 0.12, POST = 0.16;
// extra breathing room (seconds of silence to keep) after specific source times
const holdAfter = [[61.03, 0.55], [70.24, 0.35], [113.51, 0.45], [201.9, 0.2]];
const segs = [];
for (const [a, b] of spans) {
  const hold = holdAfter.find(([t]) => Math.abs(t - b) < 0.2);
  segs.push({src: a - PRE, end: b + POST + (hold ? hold[1] : 0)});
}
// merge overlapping
const merged = [];
for (const s of segs) { const l = merged[merged.length - 1]; if (l && s.src <= l.end + 0.02) l.end = Math.max(l.end, s.end); else merged.push({...s}); }
let out = 0; const clips = [];
for (const s of merged) {
  const trimBefore = Math.round(s.src * FPS), dur = Math.round((s.end - s.src) * FPS);
  clips.push({trimBefore, from: out, dur}); out += dur;
}
const mapT = (t) => { for (const c of clips) { const a = c.trimBefore / FPS, b = a + c.dur / FPS; if (t >= a - 0.001 && t <= b + 0.001) return c.from + (t - a) * FPS; } return null; };
const W = words.map((w) => ({t: w.text.trim(), f: mapT(w.start), e: mapT(w.end)})).filter((w) => w.f !== null && w.t);
fs.writeFileSync("src/vsl/data/words.ts", `// Generated by scripts/build-edl.mjs — word timings on the OUTPUT timeline (frames @30fps)\nexport const WORDS: {t: string; f: number; e: number}[] = ${JSON.stringify(W.map((w) => ({t: w.t, f: Math.round(w.f), e: Math.round(w.e)})))};\n`);
const jsx = clips.map((c, i) => `      <Video name="Take ${String(i + 1).padStart(2, "0")}" src={SRC} volume={0.9} trimBefore={${c.trimBefore}} from={${c.from}} durationInFrames={${c.dur}} />`).join("\n");
fs.writeFileSync("src/vsl/Footage.tsx", `import {Video} from '@remotion/media';
import React from 'react';
import {AbsoluteFill, staticFile} from 'remotion';

const SRC = staticFile('video/marcao.mp4');

// Edit decision list generated by scripts/build-edl.mjs:
// removes the pre-roll (0:00–0:25), the repeated "você acabou de comprar",
// dead pauses between takes, and the tail after "Te vejo do outro lado".
export const FOOTAGE_DURATION = ${out};

export const Footage: React.FC = () => (
  <AbsoluteFill>
${jsx}
  </AbsoluteFill>
);
`);
// readable transcript with output frames
let line = "", lf = 0, txt = "";
for (const w of W) { if (!line) lf = Math.round(w.f); line += " " + w.t + `@${Math.round(w.f)}`; if (/[.?!,]$/.test(w.t)) { txt += `${lf}: ${line}\n`; line = ""; } }
txt += `${lf}: ${line}\n`;
fs.writeFileSync("scripts/transcript-frames.txt", txt);
console.log("duration frames", out, (out / FPS).toFixed(1) + "s", "clips", clips.length);
