import "./index.css";
import {CalculateMetadataFunction, Composition} from 'remotion';
import {LAB_DEFAULT_PORT, LabEdit} from './lab/LabEdit';
import type {EditSpec, LabProps} from './lab/types';
import {FOOTAGE_DURATION} from './vsl/Footage';
import {VSL} from './vsl/VSL';

// In the Studio the Lab composition shows the last edit generated by the Lab server.
const labMetadata: CalculateMetadataFunction<LabProps> = async ({props, abortSignal}) => {
  let spec = props.spec;
  if (!spec && props.specUrl) {
    try {
      const res = await fetch(`${props.base ?? ''}${props.specUrl}`, {signal: abortSignal});
      if (res.ok) spec = (await res.json()) as EditSpec;
    } catch {
      spec = null;
    }
  }
  if (!spec) return {durationInFrames: 60, fps: 30, width: 1080, height: 1920, props: {...props, spec: null}};
  return {durationInFrames: spec.durationInFrames, fps: spec.fps, width: spec.width, height: spec.height, props: {...props, spec}};
};

export const RemotionRoot: React.FC = () => {
  return (
    <>
      <Composition id="VSL-Marcao" component={VSL} durationInFrames={FOOTAGE_DURATION} fps={30} width={1920} height={1080} />
      <Composition
        id="LabEdit"
        component={LabEdit}
        durationInFrames={60}
        fps={30}
        width={1080}
        height={1920}
        defaultProps={{spec: null, specUrl: '/api/current-spec', base: `http://localhost:${LAB_DEFAULT_PORT}`} satisfies LabProps}
        calculateMetadata={labMetadata}
      />
    </>
  );
};
