import {Video} from '@remotion/media';
import React from 'react';
import {AbsoluteFill, staticFile} from 'remotion';

const SRC = staticFile('video/marcao.mp4');

// Edit decision list generated by scripts/build-edl.mjs:
// removes the pre-roll (0:00–0:25), the repeated "você acabou de comprar",
// dead pauses between takes, and the tail after "Te vejo do outro lado".
export const FOOTAGE_DURATION = 6321;

export const Footage: React.FC = () => (
  <AbsoluteFill>
      <Video name="Take 01" src={SRC} volume={0.9} trimBefore={752} from={0} durationInFrames={682} />
      <Video name="Take 02" src={SRC} volume={0.9} trimBefore={1487} from={682} durationInFrames={365} />
      <Video name="Take 03" src={SRC} volume={0.9} trimBefore={1982} from={1047} durationInFrames={141} />
      <Video name="Take 04" src={SRC} volume={0.9} trimBefore={2221} from={1188} durationInFrames={459} />
      <Video name="Take 05" src={SRC} volume={0.9} trimBefore={2811} from={1647} durationInFrames={173} />
      <Video name="Take 06" src={SRC} volume={0.9} trimBefore={2988} from={1820} durationInFrames={213} />
      <Video name="Take 07" src={SRC} volume={0.9} trimBefore={3281} from={2033} durationInFrames={143} />
      <Video name="Take 08" src={SRC} volume={0.9} trimBefore={3510} from={2176} durationInFrames={812} />
      <Video name="Take 09" src={SRC} volume={0.9} trimBefore={4373} from={2988} durationInFrames={808} />
      <Video name="Take 10" src={SRC} volume={0.9} trimBefore={5265} from={3796} durationInFrames={318} />
      <Video name="Take 11" src={SRC} volume={0.9} trimBefore={5635} from={4114} durationInFrames={451} />
      <Video name="Take 12" src={SRC} volume={0.9} trimBefore={6097} from={4565} durationInFrames={417} />
      <Video name="Take 13" src={SRC} volume={0.9} trimBefore={6607} from={4982} durationInFrames={585} />
      <Video name="Take 14" src={SRC} volume={0.9} trimBefore={7231} from={5567} durationInFrames={354} />
      <Video name="Take 15" src={SRC} volume={0.9} trimBefore={7620} from={5921} durationInFrames={365} />
      <Video name="Take 16" src={SRC} volume={0.9} trimBefore={7990} from={6286} durationInFrames={35} />
  </AbsoluteFill>
);
